package com.enterprise.resilience.breaker;


import com.enterprise.resilience.exception.BusinessValidationException;
import io.github.resilience4j.circuitbreaker.CircuitBreaker;
import io.github.resilience4j.circuitbreaker.CircuitBreakerConfig;
import io.github.resilience4j.circuitbreaker.CircuitBreakerRegistry;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.time.Duration;
import java.util.function.Supplier;

@Slf4j
@Component
@RequiredArgsConstructor
public class ResilientExecutionManager {

    // Injecting the auto-configured framework registry to handle independent state structures dynamically
    private final CircuitBreakerRegistry circuitBreakerRegistry;

    /**
     * Executes a network or downstream dependency call inside an isolated bulkhead context.
     * Rather than relying on rigid annotations, this allows real-time execution context parsing.
     *
     * @param tenantId   The ID of the company/client initiating the transaction
     * @param region     The target geographical infrastructure cell (e.g., us-east, eu-west)
     * @param remoteCall The primary network transaction wrapped inside a lazy Java functional Supplier
     * @param fallback   The local fallback contingency routing block to trigger if the breaker is open
     * @return           The payload string generated by either the primary service or fallback mechanism
     */
    /**
     * Executes a network or downstream dependency call inside an isolated bulkhead context.
     */
    public <T> T executeProtectedCall(String tenantId, String region, Supplier<T> remoteCall, Supplier<T> fallback) {

        // Step 1: Compute a unique, localized isolation token key string.
        String breakerKey = String.format("cb_%s_%s", tenantId.toLowerCase(), region.toLowerCase());

        // Step 2: Retrieve or provision the circuit breaker instance for this key.
        CircuitBreaker circuitBreaker = circuitBreakerRegistry.circuitBreaker(
                breakerKey,
                () -> resolveCustomConfig(tenantId)
        );

        // Step 3: Run the action directly via the circuit breaker machine wrapper.
        // If the circuit is open, it throws a CallNotPermittedException, dropping instantly to the catch block.
        try {
            return circuitBreaker.executeSupplier(remoteCall);
        } catch (Exception throwable) {
            // This interceptor only triggers if the breaker is OPEN or a fatal network error occurred
            log.warn("Circuit Breaker [ {} ] intercepted execution failure. Falling back. Error class: {}",
                    breakerKey, throwable.getClass().getSimpleName());
            return fallback.get();
        }
    }

    /**
     * Runtime SLA Evaluation Strategy.
     * Instead of a static configuration file, this builder configures the circuit breaker dynamically
     * based on the tenant's profile.
     */
    private CircuitBreakerConfig resolveCustomConfig(String tenantId) {
        // Business Rule: Identify premium tier accounts via a prefix condition
        boolean isVip = tenantId.toUpperCase().startsWith("VIP");
        log.info("Provisioning fresh structural circuit topology profile for Tenant: {}, VIP-Status: {}", tenantId, isVip);

        return CircuitBreakerConfig.custom()
                // SLA Adjustment: High-paying VIP configurations allow a 75% error tolerance before blowing the fuse.
                // Standard configurations trip much faster (40%) to protect system resource pools from bleeding out threads.
                .failureRateThreshold(isVip ? 75.0f : 40.0f)

                // The duration the circuit breaker remains completely OPEN before transitioning to HALF_OPEN to check system health
                .waitDurationInOpenState(Duration.ofSeconds(15))

                // The number of trial requests permitted through when testing the health of a previously failed downstream service
                .permittedNumberOfCallsInHalfOpenState(3)

                // Tracks failures using a sliding ring buffer structure across the last N requests
                .slidingWindowSize(10)

                // Evaluates the sliding window based on execution execution count rather than temporal time slices
                .slidingWindowType(CircuitBreakerConfig.SlidingWindowType.COUNT_BASED)

                // The minimum volume of traffic required within the sliding window before error percentages can be calculated
                .minimumNumberOfCalls(5)

                // Strict Exception Filter List: Only network transport and infrastructure errors affect the state machine
                .recordExceptions(
                        java.net.ConnectException.class,
                        java.net.SocketTimeoutException.class,
                        org.springframework.web.client.ResourceAccessException.class,
                        RuntimeException.class
                )

                // Ignore business errors. Malformed requests or invalid parameters must not impact downstream system topology metrics.
                .ignoreExceptions(BusinessValidationException.class)

                .build();
    }
}